# Generated by Django 5.0.6 on 2026-05-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cartitem_unique_together_cartitem_milk_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="milk_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("alternative", "Alternative"),
                    ("oat", "Oat"),
                    ("coconut", "Coconut"),
                    ("banana", "Banana"),
                    ("almond", "Almond"),
                    ("none", "No milk"),
                ],
                default="regular",
                max_length=30,
            ),
        ),
    ]
