# Generated by Django 5.0.6 on 2026-05-02 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cartitem_milk_type"),
        ("catalog", "0002_product_drink_size_alter_product_product_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="combo_bakery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="combo_bakery_cart_items",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="combo_drink",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="combo_drink_cart_items",
                to="catalog.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={
                ("cart", "product", "milk_type", "combo_drink", "combo_bakery")
            },
        ),
    ]
