# Generated by Django 5.0.6 on 2026-05-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="milk_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("oat", "Oat"),
                    ("coconut", "Coconut"),
                    ("banana", "Banana"),
                    ("almond", "Almond"),
                    ("none", "No milk"),
                ],
                default="regular",
                max_length=30,
            ),
        ),
    ]
