# Generated by Django 5.0.6 on 2026-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_orderitem_milk_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="combo_bakery_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="combo_drink_name",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
