# Generated by Django 5.0.6 on 2026-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="drink_size",
            field=models.CharField(
                choices=[
                    ("none", "No size"),
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("drink", "Drink"),
                    ("bakery", "Bakery"),
                    ("beans", "Beans"),
                    ("equipment", "Equipment"),
                    ("machine_part", "Machine part"),
                    ("combo", "Combo"),
                ],
                max_length=30,
            ),
        ),
    ]
